### ISSUE TITLE
Menu inaccessible hors page d'accueil

### ISSUE THREAD

**Issue by Jaxom99** [consometers/consoherozh#1]
Bonjour,

Je remarque que sur Firefox, le menu "perso" (en haut à droite) ne fonctionne que sur la page d'accueil. 

Si on clique dessus depuis une autre page (page device linky ou MesConsentements), on ne voit pas le menu déroulant (alors que l'URL change avec "#dropdown2-header9").

Par conséquent, on est obligé de revenir à l'accueil pour se déconnecter.

**Comment by artlog** [comment]
Je pense que cela a été introduit pour supporter 'jQuery UI Touch Punch' ( commit 42e3ff974ed00c820758ba9dd638917dc97349c2 ) qui utilise une version ancienne de jquery ( jquery 1.7.1 jquery_ui 1.8.17 )
Dans la console du navigateur on peut trouver cette erreur : 
Uncaught TypeError: (intermediate value)(…) is not a function  ( https://www.consoherozh.fr/assets/application-fb56eda4b8c952ea62844f36a3685242.js:20:1) 
En revertant ce commit le menu réapparait, ( mais de nombreuses autres erreurs apparaissent dans la console). 
La librairie pour le support menu est celle d'atlassian https://aui.atlassian.com/aui/8.2/docs/dropdown2.html , il est possible qu'elle fonctionne mal avec d'anciennes versions de jquery.

**Comment by artlog** [comment]
vidéo après le revert sur mon environnement de dev : https://pire.artisanlogiciel.net/w/2f2mw2USx1mLfnEex1xZd9

**Comment by cyril-L** [comment]
Bien joué @artlog ! Pour l’historique de jQuery UI Touch Punch, c’était une tentative pour rendre Atlassian UI utilisable sur smartphone, ce qui n’était pas le cas à cause de jQuery UI. Ça ne fonctionnait pas très bien et nous avons choisi de passer d’Atlassian UI à [Bootstrap](https://getbootstrap.com/). Seul le tableau de bord à été migré pour le moment (tu peux voir la différence au niveau de la barre de menu par exemple).

Migrer le reste de l’application vers Bootstrap reste à faire (et factoriser une bonne partie de code qui est dupliquée dans `grails-app/views/layouts`), mais pour le moment ton fix fait très bien l’affaire.
